### ISSUE TITLE
Vim 向系统剪切板剪切

### ISSUE THREAD

**Issue by laixintao** [laixintao/problems#6]

**Comment by northmorn** [comment]
macOS
" Use the OS clipboard by default (on versions compiled with `+clipboard`)
set clipboard=unnamed

**Comment by laixintao** [comment]
@northmorn Thanks! It works!

Use https://github.com/laixintao/myrc/blob/e58710c4766206aa7e6c7ea4732b1fd48a151d21/.tmux.conf#L36 to copy from tmux buffer to system clipboard.

Use `set clipboard=unnamed` to share clipboard between vim and system.
